server:
  port: 8900
spring:
  cache:
    type: ehcache
    ehcache:
      config: classpath:cacheable/wxCache.xml
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wx?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
    hikari:
      minimum-idle: 20
      maximum-pool-size: 100
      pool-name: DatebookHikariCP
      max-lifetime: 60000
      auto-commit: true
      connection-timeout: 60000
      connection-test-query: select 1
      idle-timeout: 60000
      validation-timeout: 3000
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true                             #是否展示sql
    properties:
          hibernate:
            format_sql: true                   #格式化sql
    hibernate:                                 #是否自动生/更新成表，根据什么策略
      ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql

#微信相关
appid: ww*********3cb #企业ID
agentid: 1000002 #应用AgentId
redirectUri: http://**********/page/login #第三方网站获取用户信息
secret: jBuP7075r*****************5tUAMym8PQm3g #应用Secret
tongXunLuSecret: sd6CE7cAmyf***************buiLCxD7JwZS8 #通讯录Secret
# 获取token地址
accessTokenUrl: https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid={corpId}&corpsecret={corpsecret}
# 获取用户id地址
getUserIDUrl: https://qyapi.weixin.qq.com/cgi-bin/user/getuserinfo?access_token=ACCESS_TOKEN&code=CODE

# 获取用户信息地址
getUserUrl: https://qyapi.weixin.qq.com/cgi-bin/user/get?access_token=ACCESS_TOKEN&userid=USERID
# 创建用户 post
addUserUrl: https://qyapi.weixin.qq.com/cgi-bin/user/create?access_token=ACCESS_TOKEN
# 更新用户 post
updateUserUrl: https://qyapi.weixin.qq.com/cgi-bin/user/update?access_token=ACCESS_TOKEN
# 删除用户 post
delUserUrl: https://qyapi.weixin.qq.com/cgi-bin/user/delete?access_token=ACCESS_TOKEN&userid=USERID
# 批量删除用户 post
delUsersUrl: https://qyapi.weixin.qq.com/cgi-bin/user/batchdelete?access_token=ACCESS_TOKEN
# 获取部门成员 get
getDepartmentUsersUrl: https://qyapi.weixin.qq.com/cgi-bin/user/simplelist?access_token=ACCESS_TOKEN&department_id=DEPARTMENT_ID&fetch_child=FETCH_CHILD
# 获取部门成员详情信息 GET
getDepartmentUsersDetailUrl: https://qyapi.weixin.qq.com/cgi-bin/user/list?access_token=ACCESS_TOKEN&department_id=DEPARTMENT_ID&fetch_child=FETCH_CHILD

# 创建部门地址
addDepartmentUrl: https://qyapi.weixin.qq.com/cgi-bin/department/create?access_token=ACCESS_TOKEN
# 更新部门地址
updateDepartmentUrl: https://qyapi.weixin.qq.com/cgi-bin/department/update?access_token=ACCESS_TOKEN
# 删除部门地址
delDepartmentUrl: https://qyapi.weixin.qq.com/cgi-bin/department/delete?access_token=ACCESS_TOKEN&id=DEPTID
# 获取部门列表地址1（获取制定部门 部门id。获取指定部门及其下的子部门。 如果不填，默认获取全量组织架构）
getDepartmentUrl1: https://qyapi.weixin.qq.com/cgi-bin/department/list?access_token=ACCESS_TOKEN&id=ID
# 获取部门列表地址2 (获取全部 部门id。获取指定部门及其下的子部门。 如果不填，默认获取全量组织架构)
getDepartmentUrl2: https://qyapi.weixin.qq.com/cgi-bin/department/list?access_token=ACCESS_TOKEN




